export const authActionTypes = {
    SEND_LOGIN_REQUEST: 'SEND_LOGIN_REQUEST',
    SEND_LOGIN_SUCCESS: 'SEND_LOGIN_SUCCESS',
    SEND_LOGIN_FAILURE: 'SEND_LOGIN_FAILURE',

    SEND_SIGNUP_REQUEST: 'SEND_SIGNUP_REQUEST',
    SEND_SIGNUP_SUCCESS: 'SEND_SIGNUP_SUCCESS',
    SEND_SIGNUP_FAILURE: 'SEND_SIGNUP_FAILURE',

    TOGGLE_SHOW_LOGIN_FORM: 'TOGGLE_SHOW_LOGIN_FORM',
    LOGOUT: 'LOGOUT',
}

export const crawlActionTypes = {
    GET_CRAWL_DATA_REQUEST: 'GET_CRAWL_DATA_REQUEST',
    GET_CRAWL_DATA_SUCCESS: 'GET_CRAWL_DATA_SUCCESS',
    GET_CRAWL_DATA_FAILURE: 'GET_CRAWL_DATA_FAILURE',
}

export const searchActionTypes = {
    GET_SEARCH_HISTORY_REQUEST: 'GET_SEARCH_HISTORY_REQUEST',
    GET_SEARCH_HISTORY_SUCCESS: 'GET_SEARCH_HISTORY_SUCCESS',
    GET_SEARCH_HISTORY_FAILURE: 'GET_SEARCH_HISTORY_FAILURE',
}